# Generated by Django 6.0.2 on 2026-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('min_budget', models.IntegerField()),
                ('max_budget', models.IntegerField()),
                ('suitable_for', models.CharField(choices=[('solo', 'Solo'), ('family', 'Family'), ('friends', 'Friends'), ('couple', 'Couple')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
