# Generated by Django 6.0.2 on 2026-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_budget', models.IntegerField()),
                ('max_budget', models.IntegerField()),
                ('suitable_for', models.CharField(choices=[('solo', 'Solo'), ('family', 'Family'), ('friends', 'Friends'), ('couple', 'Couple')], max_length=20)),
                ('image', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
